name: Cars
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  google_fonts: ^1.1.0
  hexcolor: ^1.0.6
  eva_icons_flutter: ^2.0.0
  firebase_auth: ^0.18.3+1
  firebase_core: any
  fluttertoast: ^7.1.5
  geolocator: ^6.1.8+1
  geocoder: ^0.2.1
  camera: ^0.5.8+11
  pin_code_fields: ^6.0.1
  country_pickers: ^1.3.0
  cloud_firestore: any
  email_validator: ^1.0.6
  image_picker: ^0.6.7+14
  simple_animations: ^1.1.3
  page_transition: ^1.1.4
  firebase_storage: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/custom_icons.ttf
